---
mappings:
- alias: "ri.mio.main.media-set.b201835c-6898-44f3-9d5f-77162fdca7c5"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.mio.main.media-set.b201835c-6898-44f3-9d5f-77162fdca7c5"
