---
mappings:
- alias: "ri.magritte..source.788a5383-dc87-44e9-9e69-a956a548f26b"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.magritte..source.788a5383-dc87-44e9-9e69-a956a548f26b"
- alias: "ri.mio.main.media-set.b201835c-6898-44f3-9d5f-77162fdca7c5"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.mio.main.media-set.b201835c-6898-44f3-9d5f-77162fdca7c5"
