---
mappings:
- alias: "/Coordcode-82190b/Engineer Assistant/logic/wbdg_crawl_log"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c45b9c71-44a0-4f97-8825-861084654ca4"
- alias: "ri.foundry.main.dataset.58db10e7-d87c-4f20-a0e8-3388260681d4"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.58db10e7-d87c-4f20-a0e8-3388260681d4"
- alias: "ri.magritte..source.788a5383-dc87-44e9-9e69-a956a548f26b"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.magritte..source.788a5383-dc87-44e9-9e69-a956a548f26b"
- alias: "ri.mio.main.media-set.b201835c-6898-44f3-9d5f-77162fdca7c5"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.mio.main.media-set.b201835c-6898-44f3-9d5f-77162fdca7c5"
